version: 0.2

env:
  parameter-store:
    bucket: "key_2018_11_07"

phases:
  pre_build:
    commands:
      - echo $bucket
  build:
    commands:
    - make build
  post_build:
    commands:
    - aws cloudformation package --template-file sam.yml --s3-bucket $bucket --output-template-file build/deploy.yml
artifacts:
  type: zip
  name: 'build-artifact'
  files:
    - sam.yml
    - build/deploy.yml
