AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: deploy example

Globals:
  Function:
    Timeout: 5

Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: hello-handler
      Runtime: go1.x
      Tracing: Active
      Events:
        AppApi:
          Type: Api
          Properties:
            Path: /hello
            Method: POST
      AutoPublishAlias:
        Type: Canary10Percent15Minutes
      Role: !Ref IAMRoleForCodeDeploy

Outputs:
  AppApi:
    Description: "API Gateway endpoint URL for develop environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  AppFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt AppFunction.Arn

  AppFunctionRole:
    Description: "Implicit IAM Role created for App function"
    Value: !GetAtt AppFunctionRole.Arn
